"""change_birthday_to_date_and_fix_married_parents

Revision ID: 33fa16e2c57f
Revises: f0de2c0151a3
Create Date: 2026-05-25 09:05:28.274599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fa16e2c57f'
down_revision: Union[str, Sequence[str], None] = 'f0de2c0151a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('married_parents', sa.Boolean(), nullable=False))
    op.alter_column('patients', 'birthday',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
                postgresql_using='birthday::date')
    op.drop_column('patients', 'merried_parents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('merried_parents', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('patients', 'birthday',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('patients', 'married_parents')
    # ### end Alembic commands ###
