"""criando tabelas da clinica

Revision ID: f0de2c0151a3
Revises: 
Create Date: 2026-05-22 14:40:15.122442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0de2c0151a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('birthday', sa.String(), nullable=False),
    sa.Column('health_insurance', sa.Boolean(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('medication', sa.String(), nullable=True),
    sa.Column('merried_parents', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_table('responsibles',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('relationship_patient', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_responsibles_id'), 'responsibles', ['id'], unique=False)
    op.create_index(op.f('ix_responsibles_name'), 'responsibles', ['name'], unique=False)
    op.create_table('therapists',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_therapists_email'), 'therapists', ['email'], unique=True)
    op.create_index(op.f('ix_therapists_id'), 'therapists', ['id'], unique=False)
    op.create_index(op.f('ix_therapists_name'), 'therapists', ['name'], unique=False)
    op.create_table('paciente_responsible',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['responsibles.id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente_responsible')
    op.drop_index(op.f('ix_therapists_name'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_id'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_email'), table_name='therapists')
    op.drop_table('therapists')
    op.drop_index(op.f('ix_responsibles_name'), table_name='responsibles')
    op.drop_index(op.f('ix_responsibles_id'), table_name='responsibles')
    op.drop_table('responsibles')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
